import tianjinHuangImg from './assets/tj.png';
export const DATA = {
  lab: {
    name: 'TruGreen AI Lab',
    tagline: 'Trustworthy, Green, Efficient AI for Real-World Impact',
    contacts: {
      email: 'trugreen@exeter.ac.uk',
      address: 'Dept. of Computer Science, University of Exeter, Exeter, UK',
      twitter: 'https://x.com/',
      github: 'https://github.com/',
    },
    director: {
      name: 'Lu Liu',
      role: 'Lab Director & Principal Investigator',
      affiliation: 'University of Exeter',
      email: 'l.liu@example.exeter.ac.uk',
      img: 'https://placehold.co/240x240?text=Lu%20Liu',
      webpage: 'https://experts.exeter.ac.uk/42893-lu-liu',
    },
    pis: [
      { name: 'Tianjin Huang', role: 'Principal Investigator', affiliation: 'University of Exeter', email: 't.huang2@exeter.ac.uk', img: tianjinHuangImg, webpage:'https://tianjinyellow.github.io/'},
      { name: 'Gaojie Jin', role: 'Principal Investigator', affiliation: 'University of Exeter', email: 'g.jin@exeter.ac.uk', img: 'https://placehold.co/240x240?text=Gaojie%20Jin' },
      { name: 'Rongrui Mu', role: 'Principal Investigator', affiliation: 'University of Exeter', email: 'R.Mu2@exeter.ac.uk', img: 'https://placehold.co/240x240?text=Rongrui%20Mu' },
      { name: 'Yunxiao Zhang', role: 'Principal Investigator', affiliation: 'University of Exeter', email: 'Y.Zhang12@exeter.ac.uk', img: 'https://placehold.co/240x240?text=Yunxiao%20Zhang' },
    ],
  },
  researchAreas: [
    { title: 'Trustworthy AI', desc: 'Robustness, safety, alignment and evaluation across modalities.' },
    { title: 'Green & Efficient ML', desc: 'Energy-aware training, compression, and low-precision inference.' },
    { title: 'Sparse & Stable Optimization', desc: 'Optimizers and curricula that reduce compute and improve stability.' },
    { title: 'Applied AI', desc: 'Remote sensing, healthcare, and scientific discovery.' },
  ],
  news: [
    // Newest first.  When only the month and year are known we default the day to the 1st.
    {
      date: '2025-09-01',
      title: 'NeurIPS 2025 paper accepted',
      // Provide segments so that multiple portions of the detail can be linked individually.  The
      // segments array will override the `highlight` and `highlightUrl` fields below when
      // rendering.  Each segment has a `text` field and an optional `url`.  When `url` is
      // provided the text becomes a red, underlined link.
      detailSegments: [
        { text: 'One paper accepted at NeurIPS 2025: ' },
        { text: 'REOBench', url: 'https://arxiv.org/abs/2505.16793' },
        { text: '.' },
      ],
    },
    {
      date: '2025-05-01',
      title: 'EUSIPCO 2025 audio deepfake benchmarking',
      detail: 'Benchmarking Audio Deepfake Detection Robustness in real‑world communication scenarios accepted at EUSIPCO 2025.',
      highlight: 'EUSIPCO 2025',
      highlightUrl: 'https://arxiv.org/abs/2504.12423',
    },
    {
      date: '2025-05-01',
      title: 'REOBench released',
      detail: 'We release REOBench: a benchmark for evaluating the robustness of Earth observation foundation models.',
      highlight: 'REOBench',
      highlightUrl: 'https://github.com/lx709/reobench',
    },
    {
      date: '2025-05-01',
      title: 'MICCAI 2025 early acceptance',
      detail: 'One paper (LKA) early accepted at MICCAI 2025.',
      highlight: 'MICCAI 2025',
      highlightUrl: 'https://arxiv.org/abs/2506.19118',
    },
    {
      date: '2025-05-01',
      title: 'ICML 2025 paper accepted',
      detail: 'One paper (LIFT) accepted at ICML 2025.',
      highlight: 'ICML 2025',
      highlightUrl: 'https://arxiv.org/abs/2506.00772',
    },
    {
      date: '2025-03-01',
      title: 'Journal paper accepted',
      detail: 'A paper on traffic congestion prediction accepted by Expert Systems with Applications.',
      url: 'https://doi.org/10.1016/j.eswa.2025.127200',
      highlight: 'Expert Systems with Applications',
    },
    {
      date: '2025-03-01',
      title: 'ICLR 2025 SCOPE workshop papers',
      detail: 'Two papers accepted at the ICLR 2025 SCOPE workshop: Spike‑aware Optimizer (SPAM) and StableSPAM.',
      highlight: 'ICLR 2025 SCOPE',
    },
    {
      date: '2025-01-01',
      title: 'ICLR 2025 papers accepted',
      detailSegments: [
        { text: 'Three papers accepted at ICLR 2025: ' },
        { text: 'Spike‑aware Optimizer (SPAM)', url: 'https://arxiv.org/abs/2501.06842' },
        { text: ', ' },
        { text: 'Composable Interventions for Language Models', url: 'https://arxiv.org/abs/2407.06483' },
        { text: ', and ' },
        { text: 'Robust Fairness via Confusional Spectral Regularization', url: 'https://arxiv.org/abs/2501.13273' },
        { text: '.' },
      ],
      // highlight can be retained for compatibility, but it’s ignored when detailSegments is present
      highlight: 'ICLR 2025',
    },
    {
      date: '2024-12-01',
      title: 'Invited talk at SGAI',
      detail: 'Invited talk delivered at the SGAI conference in Cambridge on benchmarking the robustness of remote sensing foundation models.',
      url: 'https://www.bcs.org/events-calendar/2025/april/webinar-sgai-virtual-seminar-series-2025-computer-vision-applications/',
    },
    {
      date: '2024-12-01',
      title: 'AAAI 2025 paper accepted',
      detail: 'Visual prompting upgrades neural network sparsification: a data‑model perspective accepted at AAAI 2025.',
      highlight: 'AAAI 2025',
      highlightUrl: 'https://arxiv.org/abs/2312.01397',
    },
    {
      date: '2024-07-01',
      title: 'BMVC 2024 paper accepted',
      detail: 'Are Sparse Neural Networks Better Hard Sample Learners? accepted at BMVC 2024.',
      highlight: 'BMVC',
      highlightUrl: 'https://arxiv.org/abs/2409.09196',
    },
    {
      date: '2024-06-01',
      title: 'Co‑organizing NeurIPS 2024 Edge‑Device competition',
      detail: 'Co‑organizing the NeurIPS 2024 Edge‑Device Large Language Model Competition. Join us for the competition!',
      url: 'https://edge-llms-challenge.github.io/',
      highlight: 'the competition',
      highlightUrl: 'https://edge-llms-challenge.github.io/',
    },
    {
      date: '2024-03-01',
      title: 'ICLR 2024 workshop paper accepted',
      detail: 'Composing Knowledge and Compression Interventions for Language Models accepted at an ICLR 2024 workshop.',
      highlight: 'ICLR 2024 workshop',
      highlightUrl: 'https://openreview.net/forum?id=quK3DN5kUO',
    },
    {
      date: '2023-10-01',
      title: 'Information Fusion paper accepted',
      detail: 'Robust Spatiotemporal GCN accepted in Information Fusion. IF=18.5',
      highlight: 'Information Fusion',
      highlightUrl: 'https://doi.org/10.1016/j.inffus.2023.102078',
    },
    {
      date: '2023-09-01',
      title: 'Complex Networks 2024 paper accepted',
      detail: 'Heterophily‑Based Graph Neural Network for Imbalanced Classification accepted in Complex Networks 2024.',
      highlight: 'Heterophily‑Based Graph Neural Network',
      highlightUrl: 'https://arxiv.org/abs/2310.08725',
    },
    {
      date: '2023-09-01',
      title: 'NeurIPS 2023 paper accepted',
      detail: 'Channel‑DST accepted at NeurIPS 2023.',
      highlight: 'NeurIPS 2023',
      highlightUrl: 'https://arxiv.org/abs/2305.19454',
    },
    {
      date: '2023-06-01',
      title: 'ECML 2023 paper accepted',
      detail: 'Enhancing AT via Refining Optimization Trajectories accepted at ECML 2023.',
      highlight: 'ECML 2023',
      highlightUrl: 'https://arxiv.org/abs/2306.14275',
    },
    {
      date: '2023-04-01',
      title: 'ICML 2023 paper accepted',
      detail: 'Larger Kernel Serve better Teachers than Transformers accepted at ICML 2023.',
      highlight: 'ICML 2023',
      highlightUrl: 'https://arxiv.org/abs/2305.19412',
    },
    {
      date: '2023-01-01',
      title: 'ICLR 2023 paper accepted',
      detail: 'Oral paper “Sparsity May Cry: SMC” accepted at ICLR 2023.',
      highlight: 'ICLR 2023',
      highlightUrl: 'https://arxiv.org/abs/2303.02141',
    },
    {
      date: '2022-11-01',
      title: 'LoG 2022 Best Paper Award',
      detail: 'Better GNN by Finding Graph Tickets accepted at LoG 2022 with a Best Paper Award.',
      highlight: 'Best Paper Award.',
      highlightUrl: 'https://arxiv.org/abs/2211.15335',
    },
    {
      date: '2022-11-01',
      title: 'AAAI 2023 paper accepted',
      detail: 'Lottery Pools accepted at AAAI 2023.',
      highlight: 'AAAI 2023',
      highlightUrl: 'https://arxiv.org/abs/2208.10842',
    },
    {
      date: '2022-06-01',
      title: 'ECML‑PKDD 2022 paper accepted',
      detail: 'Hop‑count based self‑supervised anomaly detection accepted at ECML‑PKDD 2022.',
      highlight: 'ECML‑PKDD',
      highlightUrl: 'https://arxiv.org/abs/2104.07917',
    },
  ],
  publications: [
    { year: 2025, title: 'Stable Sparse Training for LLMs', authors: 'Liu*, Huang*, Jin, Mu, Zhang', venue: 'Preprint', link: '#' },
  ],
  resources: [
    { label: 'Open Positions', url: '#/contact' },
    { label: 'Code & Datasets', url: 'https://github.com/' },
    { label: 'Seminar Series', url: '#/news' },
  ],
}
