export const DATA = {
  lab: {
    name: 'TruGreen AI Lab',
    tagline: 'Trustworthy, Green, Efficient AI for Real-World Impact',
    contacts: {
      email: 'trugreen@exeter.ac.uk',
      address: 'Dept. of Computer Science, University of Exeter, Exeter, UK',
      twitter: 'https://x.com/',
      github: 'https://github.com/',
    },
    director: {
      name: 'Lu Liu',
      role: 'Lab Director & Principal Investigator',
      affiliation: 'University of Exeter',
      email: 'l.liu@example.exeter.ac.uk',
      img: 'https://placehold.co/240x240?text=Lu%20Liu',
    },
    pis: [
      { name: 'Tianjin Huang', role: 'Principal Investigator', affiliation: 'University of Exeter', email: 't.huang2@exeter.ac.uk', img: 'https://placehold.co/240x240?text=Tianjin%20Huang' },
      { name: 'Gaojie Jin', role: 'Principal Investigator', affiliation: 'University of Exeter', email: '', img: 'https://placehold.co/240x240?text=Gaojie%20Jin' },
      { name: 'Rongrui Mu', role: 'Principal Investigator', affiliation: 'University of Exeter', email: '', img: 'https://placehold.co/240x240?text=Rongrui%20Mu' },
      { name: 'Yunxiao Zhang', role: 'Principal Investigator', affiliation: 'University of Exeter', email: '', img: 'https://placehold.co/240x240?text=Yunxiao%20Zhang' },
    ],
  },
  researchAreas: [
    { title: 'Trustworthy AI', desc: 'Robustness, safety, alignment and evaluation across modalities.' },
    { title: 'Green & Efficient ML', desc: 'Energy-aware training, compression, and low-precision inference.' },
    { title: 'Sparse & Stable Optimization', desc: 'Optimizers and curricula that reduce compute and improve stability.' },
    { title: 'Applied AI', desc: 'Remote sensing, Healthcare, and Scientific discovery.' },
  ],
  news: [
    // Newest first.  When only the month and year are known we default the day to the 1st.
    { date: '2025-10-02', title: 'TruGreen AI Lab site launched', detail: 'First cohort and partners incoming.' },
    { date: '2025-10-01', title: 'Seed projects kick off', detail: 'Pilots on stable sparse training and robust GNNs.' },
    { date: '2025-09-01', title: 'NeurIPS 2025 paper accepted', detail: 'One paper accepted at NeurIPS 2025: REOBench.' },
    { date: '2025-05-01', title: 'EUSIPCO 2025 audio deepfake benchmarking', detail: 'Benchmarking Audio Deepfake Detection Robustness in real-world communication scenarios accepted at EUSIPCO 2025.' },
    { date: '2025-05-01', title: 'REOBench released', detail: 'We release REOBench: a benchmark for evaluating the robustness of Earth observation foundation models.' },
    { date: '2025-05-01', title: 'MICCAI 2025 early acceptance', detail: 'One paper (LKA) early accepted at MICCAI 2025.' },
    { date: '2025-05-01', title: 'ICML 2025 paper accepted', detail: 'One paper (LIFT) accepted at ICML 2025.' },
    { date: '2025-03-01', title: 'Journal paper accepted', detail: 'A paper on traffic congestion prediction accepted by Expert Systems with Applications.' },
    { date: '2025-03-01', title: 'ICLR 2025 SCOPE workshop papers', detail: 'Two papers accepted at the ICLR 2025 SCOPE workshop: Spike‑aware Optimizer (SPAM) and StableSPAM.' },
    { date: '2025-01-01', title: 'ICLR 2025 papers accepted', detail: 'Three papers accepted at ICLR 2025: Spike‑aware Optimizer (SPAM), Composable Interventions for Language Models, and Robust Fairness via Confusional Spectral Regularization.' },
    { date: '2024-12-01', title: 'Invited talk at SGAI', detail: 'Invited talk delivered at the SGAI conference in the University of Cambridge.' },
    { date: '2024-12-01', title: 'AAAI 2025 paper accepted', detail: 'Visual prompting upgrades neural network sparsification: a data‑model perspective accepted at AAAI 2025.' },
    { date: '2024-07-01', title: 'BMVC 2024 paper accepted', detail: 'Are Sparse Neural Networks Better Hard Sample Learners? accepted at BMVC 2024.' },
    { date: '2024-06-01', title: 'Co‑organizing NeurIPS 2024 Edge‑Device competition', detail: 'Co‑organizing the NeurIPS 2024 Edge‑Device Large Language Model Competition; join us for the competition!' },
    { date: '2024-03-01', title: 'ICLR 2024 workshop paper accepted', detail: 'Composing Knowledge and Compression Interventions for Language Models accepted at an ICLR 2024 workshop.' },
    { date: '2023-10-01', title: 'Information Fusion paper accepted', detail: 'Robust Spatiotemporal GCN accepted in Information Fusion.' },
    { date: '2023-09-01', title: 'Complex Networks 2024 paper accepted', detail: 'Heterophily‑Based Graph Neural Network for Imbalanced Classification accepted in Complex Networks 2024.' },
    { date: '2023-09-01', title: 'NeurIPS 2023 paper accepted', detail: 'Channel‑DST accepted at NeurIPS 2023.' },
    { date: '2023-06-01', title: 'ECML 2023 paper accepted', detail: 'Enhancing AT via Refining Optimization Trajectories accepted at ECML 2023.' },
    { date: '2023-04-01', title: 'ICML 2023 paper accepted', detail: 'Larger Kernel Serve better Teachers than Transformers accepted at ICML 2023.' },
    { date: '2023-01-01', title: 'ICLR 2023 paper accepted', detail: 'Oral paper “Sparsity May Cry: SMC” accepted at ICLR 2023.' },
    { date: '2022-11-01', title: 'LoG 2022 Best Paper Award', detail: 'Better GNN by Finding Graph Tickets accepted at LoG 2022 with a Best Paper Award.' },
    { date: '2022-11-01', title: 'AAAI 2023 paper accepted', detail: 'Lottery Pools accepted at AAAI 2023.' },
    { date: '2022-06-01', title: 'ECML‑PKDD 2022 paper accepted', detail: 'Hop‑count based self‑supervised anomaly detection accepted at ECML‑PKDD 2022.' },
  ],
  publications: [
    { year: 2025, title: 'Stable Sparse Training for LLMs', authors: 'Liu*, Huang*, Jin, Mu, Zhang', venue: 'Preprint', link: '#' },
  ],
  resources: [
    { label: 'Open Positions', url: '#/contact' },
    { label: 'Code & Datasets', url: 'https://github.com/' },
    { label: 'Seminar Series', url: '#/news' },
  ],
}
